MAP_MAPPING = {
    ["2"] = {"Floor 1"}, -- Foyer
    ["31"] = {"Floor 2"}, -- Upper Foyer
    ["36"] = {"Floor 2"}, -- Parlor
    ["42"] = {"Floor 2"}, -- Anteroom
    ["41"] = {"Floor 2"}, -- Wardrobe
    ["40"] = {"Floor 2"}, -- Wardrobe Balcony
    ["35"] = {"Floor 2"}, -- Study
    ["34"] = {"Floor 2"}, -- Master Bedroom
    ["26"] = {"Floor 2"}, -- Nursery
    ["27"] = {"Floor 2"}, -- Twins
    ["6"] = {"Floor 1"}, -- Floor 1 Hallway
    ["17"] = {"Floor 1"}, -- Rear Floor 1 Hallway
    ["21"] = {"Floor 1"}, -- Floor 1 Bathroom
    ["16"] = {"Floor 1"}, -- Floor 1 Washroom
    ["9"] = {"Floor 1"}, -- Ballroom
    ["14"] = {"Floor 1"}, -- Storage
    ["3"] = {"Floor 1"}, -- Fortune
    ["4"] = {"Floor 1"}, -- Mirror
    ["5"] = {"Floor 1"}, -- Laundry
    ["0"] = {"Floor 1"}, -- Butler
    ["1"] = {"Floor 1"}, -- Hidden Room
    ["22"] = {"Floor 1"}, -- Conservatory
    ["8"] = {"Floor 1"}, -- Dining
    ["7"] = {"Floor 1"}, -- Kitchen
    ["11"] = {"Floor 1"}, -- Boneyard
    ["15"] = {"Floor 1"}, -- Graveyard
    ["24"] = {"Floor 1"}, -- Courtyard
    ["72"] = {"Basement"}, -- The Well
    ["23"] = {"Floor 1"}, -- Rec Room
    ["18"] = {"Floor 2"}, -- 2F Stairwell
    ["50"] = {"Floor 2"}, -- Tea Room
    ["33"] = {"Floor 3"}, -- 3F stairwell
    ["46"] = {"Floor 2"}, -- Rear 2F Hallway
    ["32"] = {"Floor 2"}, -- Rear 2F Hallway
    ["45"] = {"Floor 2"}, -- 2F Washroom
    ["48"] = {"Floor 2"}, -- 2F Bathroom
    ["49"] = {"Floor 2"}, -- Nana
    ["43"] = {"Floor 2"}, -- Astral
    ["44"] = {"Floor 2"}, -- Observatory
    ["12"] = {"Floor 1"}, -- Billiards
    ["13"] = {"Floor 1"}, -- Projection
    ["55"] = {"Floor 3"}, -- Safari
    ["62"] = {"Floor 3"}, -- Balcony
    ["69"] = {"Basement"}, -- Breaker (nice)
    ["66"] = {"Basement"}, -- Cellar
    ["53"] = {"Floor 3"}, -- Telephone
    ["59"] = {"Floor 3"}, -- Clockwork
    ["63"] = {"Roof"},
    ["51"] = {"Floor 3"}, -- Armory
    ["58"] = {"Floor 3"}, -- Ceramics
    ["37"] = {"Floor 2"}, -- Sealed Room
    ["28"] = {"Floor 2"}, -- Sitting
    ["29"] = {"Floor 2"}, -- Guest
    ["64"] = {"Basement"}, -- Cold Storage
    ["68"] = {"Basement"}, -- Pipe Room
    ["67"] = {"Basement"}, -- Basement Stairwell
    ["60"] = {"Floor 3"}, -- Artist
    ["73"] = {"Basement"}, -- Secret Altar
    ["71"] = {"Basement"}, -- Spade Hallway
    ["54"] = {"Floor 3"}, -- East Attic
    ["57"] = {"Floor 3"}, -- West Attic
}